modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="grenadier"
version="${mod_version}"
displayName="掷弹兵"
description='''
Adds tactical throwable items, reusable signal beacons, smoke concealment AI, and shared server rule hooks.
'''

[[mixins]]
config="grenadier.mixins.json"

[[dependencies.grenadier]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.grenadier]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.grenadier]]
modId="veil"
type="required"
versionRange="[${veil_version},5.0.0)"
ordering="AFTER"
side="CLIENT"
