modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="grenadier"
version="${mod_version}"
displayName="掷弹兵"
authors="DarkraiEMM"
displayURL="https://github.com/DarkraiEMM/Grenadier"
issueTrackerURL="https://github.com/DarkraiEMM/Grenadier/issues"
logoFile="grenadier.png"
description='''
Adds tactical grenades, deployable mines, volumetric smoke concealment, and a reusable signal beacon.
'''

[[mixins]]
config="grenadier.mixins.json"

[[dependencies.grenadier]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.grenadier]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.grenadier]]
modId="veil"
type="required"
versionRange="[${veil_version},5.0.0)"
ordering="AFTER"
side="CLIENT"
